// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Touchpoint.Cms.Integrations.ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CreateDocumentArgs
    {
        /// <summary>
        /// Initializes a new instance of the CreateDocumentArgs class.
        /// </summary>
        public CreateDocumentArgs() { }

        /// <summary>
        /// Initializes a new instance of the CreateDocumentArgs class.
        /// </summary>
        public CreateDocumentArgs(string format = default(string), IDictionary<string, object> deviceInfo = default(IDictionary<string, object>), bool? useCache = default(bool?), string baseDocumentID = default(string), string actionID = default(string))
        {
            Format = format;
            DeviceInfo = deviceInfo;
            UseCache = useCache;
            BaseDocumentID = baseDocumentID;
            ActionID = actionID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Format")]
        public string Format { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeviceInfo")]
        public IDictionary<string, object> DeviceInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UseCache")]
        public bool? UseCache { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseDocumentID")]
        public string BaseDocumentID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActionID")]
        public string ActionID { get; set; }

    }
}
