// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Touchpoint.Cms.Integrations.ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MobileWorkOrderEditCosts
    {
        /// <summary>
        /// Initializes a new instance of the MobileWorkOrderEditCosts class.
        /// </summary>
        public MobileWorkOrderEditCosts() { }

        /// <summary>
        /// Initializes a new instance of the MobileWorkOrderEditCosts class.
        /// </summary>
        public MobileWorkOrderEditCosts(long? workOrderId = default(long?), long? workOrderNumber = default(long?), double? estimatedMaterialsCost = default(double?), double? estimatedLaborCost = default(double?), double? actualMaterialsCost = default(double?), double? actualLaborCost = default(double?))
        {
            WorkOrderId = workOrderId;
            WorkOrderNumber = workOrderNumber;
            EstimatedMaterialsCost = estimatedMaterialsCost;
            EstimatedLaborCost = estimatedLaborCost;
            ActualMaterialsCost = actualMaterialsCost;
            ActualLaborCost = actualLaborCost;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderId")]
        public long? WorkOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderNumber")]
        public long? WorkOrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EstimatedMaterialsCost")]
        public double? EstimatedMaterialsCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EstimatedLaborCost")]
        public double? EstimatedLaborCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActualMaterialsCost")]
        public double? ActualMaterialsCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActualLaborCost")]
        public double? ActualLaborCost { get; set; }

    }
}
