// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Touchpoint.Cms.Integrations.ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MobileWorkOrderEditGeneralInfo
    {
        /// <summary>
        /// Initializes a new instance of the MobileWorkOrderEditGeneralInfo
        /// class.
        /// </summary>
        public MobileWorkOrderEditGeneralInfo() { }

        /// <summary>
        /// Initializes a new instance of the MobileWorkOrderEditGeneralInfo
        /// class.
        /// </summary>
        public MobileWorkOrderEditGeneralInfo(IList<MobileTreeNode> items = default(IList<MobileTreeNode>), long? workOrderId = default(long?), int? workOrderNumber = default(int?), long? locationId = default(long?), long? serviceCategoryId = default(long?), long? workOrderPriorityId = default(long?), string description = default(string), string requestor = default(string), string location = default(string), string schedulableItems = default(string), int? workOrderStatusId = default(int?), string rejectionReason = default(string), string holdReason = default(string), string accountName = default(string), long? accountId = default(long?), bool? isAssignedViewOnly = default(bool?), bool? isAssignedUser = default(bool?), bool? isAssignedDept = default(bool?), bool? isDeletable = default(bool?), bool? isAdmin = default(bool?), bool? hasManageWoPermission = default(bool?), bool? canCloseWo = default(bool?), long? inventoryItemType = default(long?), bool? canTransferWork = default(bool?), DateTime? eta = default(DateTime?), DateTime? endDate = default(DateTime?), IList<SelectListItem> serviceCategories = default(IList<SelectListItem>), IList<SelectListItem> priorities = default(IList<SelectListItem>), IList<MobileUserDefinedField> udfs = default(IList<MobileUserDefinedField>), IList<SelectListItem> workOrderStatusOpts = default(IList<SelectListItem>), string serviceCategory = default(string), string priority = default(string), string equipmentDisplayString = default(string), string spacesString = default(string), ServiceCategoryFormsApi serviceCategoryForms = default(ServiceCategoryFormsApi))
        {
            Items = items;
            WorkOrderId = workOrderId;
            WorkOrderNumber = workOrderNumber;
            LocationId = locationId;
            ServiceCategoryId = serviceCategoryId;
            WorkOrderPriorityId = workOrderPriorityId;
            Description = description;
            Requestor = requestor;
            Location = location;
            SchedulableItems = schedulableItems;
            WorkOrderStatusId = workOrderStatusId;
            RejectionReason = rejectionReason;
            HoldReason = holdReason;
            AccountName = accountName;
            AccountId = accountId;
            IsAssignedViewOnly = isAssignedViewOnly;
            IsAssignedUser = isAssignedUser;
            IsAssignedDept = isAssignedDept;
            IsDeletable = isDeletable;
            IsAdmin = isAdmin;
            HasManageWoPermission = hasManageWoPermission;
            CanCloseWo = canCloseWo;
            InventoryItemType = inventoryItemType;
            CanTransferWork = canTransferWork;
            Eta = eta;
            EndDate = endDate;
            ServiceCategories = serviceCategories;
            Priorities = priorities;
            Udfs = udfs;
            WorkOrderStatusOpts = workOrderStatusOpts;
            ServiceCategory = serviceCategory;
            Priority = priority;
            EquipmentDisplayString = equipmentDisplayString;
            SpacesString = spacesString;
            ServiceCategoryForms = serviceCategoryForms;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Items")]
        public IList<MobileTreeNode> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderId")]
        public long? WorkOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderNumber")]
        public int? WorkOrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LocationId")]
        public long? LocationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceCategoryId")]
        public long? ServiceCategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderPriorityId")]
        public long? WorkOrderPriorityId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Requestor")]
        public string Requestor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SchedulableItems")]
        public string SchedulableItems { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderStatusId")]
        public int? WorkOrderStatusId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RejectionReason")]
        public string RejectionReason { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HoldReason")]
        public string HoldReason { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountName")]
        public string AccountName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountId")]
        public long? AccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAssignedViewOnly")]
        public bool? IsAssignedViewOnly { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAssignedUser")]
        public bool? IsAssignedUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAssignedDept")]
        public bool? IsAssignedDept { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsDeletable")]
        public bool? IsDeletable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAdmin")]
        public bool? IsAdmin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HasManageWoPermission")]
        public bool? HasManageWoPermission { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CanCloseWo")]
        public bool? CanCloseWo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InventoryItemType")]
        public long? InventoryItemType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CanTransferWork")]
        public bool? CanTransferWork { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Eta")]
        public DateTime? Eta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndDate")]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceCategories")]
        public IList<SelectListItem> ServiceCategories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Priorities")]
        public IList<SelectListItem> Priorities { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Udfs")]
        public IList<MobileUserDefinedField> Udfs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderStatusOpts")]
        public IList<SelectListItem> WorkOrderStatusOpts { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceCategory")]
        public string ServiceCategory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Priority")]
        public string Priority { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EquipmentDisplayString")]
        public string EquipmentDisplayString { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SpacesString")]
        public string SpacesString { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceCategoryForms")]
        public ServiceCategoryFormsApi ServiceCategoryForms { get; set; }

    }
}
