// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Touchpoint.Cms.Integrations.ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MobileWoAddAttachment
    {
        /// <summary>
        /// Initializes a new instance of the MobileWoAddAttachment class.
        /// </summary>
        public MobileWoAddAttachment() { }

        /// <summary>
        /// Initializes a new instance of the MobileWoAddAttachment class.
        /// </summary>
        public MobileWoAddAttachment(long? workOrderId = default(long?), string fileName = default(string), byte[] content = default(byte[]))
        {
            WorkOrderId = workOrderId;
            FileName = fileName;
            Content = content;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderId")]
        public long? WorkOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Content")]
        public byte[] Content { get; set; }

    }
}
