// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Touchpoint.Cms.Integrations.ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class WebHookCreateApiModel
    {
        /// <summary>
        /// Initializes a new instance of the WebHookCreateApiModel class.
        /// </summary>
        public WebHookCreateApiModel() { }

        /// <summary>
        /// Initializes a new instance of the WebHookCreateApiModel class.
        /// </summary>
        public WebHookCreateApiModel(string url, long? id = default(long?), string notes = default(string), IList<int?> eventIds = default(IList<int?>))
        {
            Id = id;
            Url = url;
            Notes = notes;
            EventIds = eventIds;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Notes")]
        public string Notes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EventIds")]
        public IList<int?> EventIds { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Url == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Url");
            }
        }
    }
}
