// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Touchpoint.Cms.Integrations.ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class WoTask
    {
        /// <summary>
        /// Initializes a new instance of the WoTask class.
        /// </summary>
        public WoTask() { }

        /// <summary>
        /// Initializes a new instance of the WoTask class.
        /// </summary>
        public WoTask(long? id = default(long?), long? workOrderId = default(long?), DateTime? dueDate = default(DateTime?), DateTime? dateCompleted = default(DateTime?), string description = default(string), bool? isCompleted = default(bool?), int? priority = default(int?), long? assignedToUserId = default(long?), string assignedToUserFullName = default(string), long? completedByUserId = default(long?), string completedByUserFullName = default(string))
        {
            Id = id;
            WorkOrderId = workOrderId;
            DueDate = dueDate;
            DateCompleted = dateCompleted;
            Description = description;
            IsCompleted = isCompleted;
            Priority = priority;
            AssignedToUserId = assignedToUserId;
            AssignedToUserFullName = assignedToUserFullName;
            CompletedByUserId = completedByUserId;
            CompletedByUserFullName = completedByUserFullName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderId")]
        public long? WorkOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DueDate")]
        public DateTime? DueDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCompleted")]
        public DateTime? DateCompleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsCompleted")]
        public bool? IsCompleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Priority")]
        public int? Priority { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssignedToUserId")]
        public long? AssignedToUserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssignedToUserFullName")]
        public string AssignedToUserFullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CompletedByUserId")]
        public long? CompletedByUserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CompletedByUserFullName")]
        public string CompletedByUserFullName { get; set; }

    }
}
