// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ClientReportSource
    {
        /// <summary>
        /// Initializes a new instance of the ClientReportSource class.
        /// </summary>
        public ClientReportSource() { }

        /// <summary>
        /// Initializes a new instance of the ClientReportSource class.
        /// </summary>
        public ClientReportSource(string report = default(string), IDictionary<string, object> parameterValues = default(IDictionary<string, object>))
        {
            Report = report;
            ParameterValues = parameterValues;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Report")]
        public string Report { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ParameterValues")]
        public IDictionary<string, object> ParameterValues { get; set; }

    }
}
