// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EventInfo
    {
        /// <summary>
        /// Initializes a new instance of the EventInfo class.
        /// </summary>
        public EventInfo() { }

        /// <summary>
        /// Initializes a new instance of the EventInfo class.
        /// </summary>
        public EventInfo(long? id = default(long?), string name = default(string), bool? isPublic = default(bool?), string category = default(string), bool? isRecurring = default(bool?), string publicLink = default(string), string publicNotes = default(string), IList<OccurrenceInfo> occurrences = default(IList<OccurrenceInfo>))
        {
            Id = id;
            Name = name;
            IsPublic = isPublic;
            Category = category;
            IsRecurring = isRecurring;
            PublicLink = publicLink;
            PublicNotes = publicNotes;
            Occurrences = occurrences;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsPublic")]
        public bool? IsPublic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsRecurring")]
        public bool? IsRecurring { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PublicLink")]
        public string PublicLink { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PublicNotes")]
        public string PublicNotes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Occurrences")]
        public IList<OccurrenceInfo> Occurrences { get; set; }

    }
}
