// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EventAddNewContactModel
    {
        /// <summary>
        /// Initializes a new instance of the EventAddNewContactModel class.
        /// </summary>
        public EventAddNewContactModel() { }

        /// <summary>
        /// Initializes a new instance of the EventAddNewContactModel class.
        /// </summary>
        public EventAddNewContactModel(string firstName = default(string), string lastName = default(string), string company = default(string), string email = default(string), string phoneNumber = default(string), bool? saveContactForFutureUse = default(bool?))
        {
            FirstName = firstName;
            LastName = lastName;
            Company = company;
            Email = email;
            PhoneNumber = phoneNumber;
            SaveContactForFutureUse = saveContactForFutureUse;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Company")]
        public string Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SaveContactForFutureUse")]
        public bool? SaveContactForFutureUse { get; set; }

    }
}
