// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EventItemFormApiModel
    {
        /// <summary>
        /// Initializes a new instance of the EventItemFormApiModel class.
        /// </summary>
        public EventItemFormApiModel() { }

        /// <summary>
        /// Initializes a new instance of the EventItemFormApiModel class.
        /// </summary>
        public EventItemFormApiModel(string formName = default(string), long? scheduledItemId = default(long?), long? formVersionId = default(long?), long? scheduleId = default(long?), long? eventId = default(long?), bool? isEditable = default(bool?), IList<FormBuilderQuestion> questions = default(IList<FormBuilderQuestion>))
        {
            FormName = formName;
            ScheduledItemId = scheduledItemId;
            FormVersionId = formVersionId;
            ScheduleId = scheduleId;
            EventId = eventId;
            IsEditable = isEditable;
            Questions = questions;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FormName")]
        public string FormName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ScheduledItemId")]
        public long? ScheduledItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FormVersionId")]
        public long? FormVersionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ScheduleId")]
        public long? ScheduleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EventId")]
        public long? EventId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsEditable")]
        public bool? IsEditable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Questions")]
        public IList<FormBuilderQuestion> Questions { get; set; }

    }
}
