// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FormBuilderOption
    {
        /// <summary>
        /// Initializes a new instance of the FormBuilderOption class.
        /// </summary>
        public FormBuilderOption() { }

        /// <summary>
        /// Initializes a new instance of the FormBuilderOption class.
        /// </summary>
        public FormBuilderOption(int? id = default(int?), string name = default(string), string value = default(string), long? questionId = default(long?), bool? isChecked = default(bool?))
        {
            Id = id;
            Name = name;
            Value = value;
            QuestionId = questionId;
            IsChecked = isChecked;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuestionId")]
        public long? QuestionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsChecked")]
        public bool? IsChecked { get; set; }

    }
}
