// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FormBuilderAnswer
    {
        /// <summary>
        /// Initializes a new instance of the FormBuilderAnswer class.
        /// </summary>
        public FormBuilderAnswer() { }

        /// <summary>
        /// Initializes a new instance of the FormBuilderAnswer class.
        /// </summary>
        public FormBuilderAnswer(long? id = default(long?), long? scheduledItemid = default(long?), long? questionId = default(long?), string value = default(string))
        {
            Id = id;
            ScheduledItemid = scheduledItemid;
            QuestionId = questionId;
            Value = value;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ScheduledItemid")]
        public long? ScheduledItemid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuestionId")]
        public long? QuestionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

    }
}
