// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FormBuilderQuestion
    {
        /// <summary>
        /// Initializes a new instance of the FormBuilderQuestion class.
        /// </summary>
        public FormBuilderQuestion() { }

        /// <summary>
        /// Initializes a new instance of the FormBuilderQuestion class.
        /// </summary>
        public FormBuilderQuestion(long? id = default(long?), long? formVersionId = default(long?), int? sequence = default(int?), string text = default(string), string questionType = default(string), bool? isRequired = default(bool?), bool? showBlankOption = default(bool?), string linkUrl = default(string), string linkText = default(string), bool? isDeleted = default(bool?), string textAnswer = default(string), IList<FormBuilderOption> options = default(IList<FormBuilderOption>), IList<FormBuilderAnswer> answers = default(IList<FormBuilderAnswer>))
        {
            Id = id;
            FormVersionId = formVersionId;
            Sequence = sequence;
            Text = text;
            QuestionType = questionType;
            IsRequired = isRequired;
            ShowBlankOption = showBlankOption;
            LinkUrl = linkUrl;
            LinkText = linkText;
            IsDeleted = isDeleted;
            TextAnswer = textAnswer;
            Options = options;
            Answers = answers;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FormVersion_id")]
        public long? FormVersionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sequence")]
        public int? Sequence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuestionType")]
        public string QuestionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsRequired")]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShowBlankOption")]
        public bool? ShowBlankOption { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LinkUrl")]
        public string LinkUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LinkText")]
        public string LinkText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TextAnswer")]
        public string TextAnswer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Options")]
        public IList<FormBuilderOption> Options { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Answers")]
        public IList<FormBuilderAnswer> Answers { get; set; }

    }
}
