// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ItemConfigurationApiModel
    {
        /// <summary>
        /// Initializes a new instance of the ItemConfigurationApiModel class.
        /// </summary>
        public ItemConfigurationApiModel() { }

        /// <summary>
        /// Initializes a new instance of the ItemConfigurationApiModel class.
        /// </summary>
        public ItemConfigurationApiModel(long? id = default(long?), string name = default(string), string thumbnail = default(string), string originalImage = default(string), string type = default(string), int? typeEnum = default(int?), bool? isChecked = default(bool?))
        {
            Id = id;
            Name = name;
            Thumbnail = thumbnail;
            OriginalImage = originalImage;
            Type = type;
            TypeEnum = typeEnum;
            IsChecked = isChecked;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Thumbnail")]
        public string Thumbnail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OriginalImage")]
        public string OriginalImage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TypeEnum")]
        public int? TypeEnum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsChecked")]
        public bool? IsChecked { get; set; }

    }
}
