// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MobileUserDefinedField
    {
        /// <summary>
        /// Initializes a new instance of the MobileUserDefinedField class.
        /// </summary>
        public MobileUserDefinedField() { }

        /// <summary>
        /// Initializes a new instance of the MobileUserDefinedField class.
        /// </summary>
        public MobileUserDefinedField(long? id = default(long?), string label = default(string), string value = default(string), bool? isRequired = default(bool?), bool? isExisting = default(bool?), long? udfDetailId = default(long?), bool? displayOnWoRequestForm = default(bool?))
        {
            Id = id;
            Label = label;
            Value = value;
            IsRequired = isRequired;
            IsExisting = isExisting;
            UdfDetailId = udfDetailId;
            DisplayOnWoRequestForm = displayOnWoRequestForm;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsRequired")]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsExisting")]
        public bool? IsExisting { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UdfDetailId")]
        public long? UdfDetailId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DisplayOnWoRequestForm")]
        public bool? DisplayOnWoRequestForm { get; set; }

    }
}
