// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MobileWorkOrderAdditionalDetails
    {
        /// <summary>
        /// Initializes a new instance of the MobileWorkOrderAdditionalDetails
        /// class.
        /// </summary>
        public MobileWorkOrderAdditionalDetails() { }

        /// <summary>
        /// Initializes a new instance of the MobileWorkOrderAdditionalDetails
        /// class.
        /// </summary>
        public MobileWorkOrderAdditionalDetails(long? workOrderId = default(long?), double? projectedHours = default(double?), double? actualHours = default(double?), IList<long?> selectedEquipmentIds = default(IList<long?>), IList<SelectListItem> equipmentList = default(IList<SelectListItem>), long? workOrderNumber = default(long?))
        {
            WorkOrderId = workOrderId;
            ProjectedHours = projectedHours;
            ActualHours = actualHours;
            SelectedEquipmentIds = selectedEquipmentIds;
            EquipmentList = equipmentList;
            WorkOrderNumber = workOrderNumber;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderId")]
        public long? WorkOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProjectedHours")]
        public double? ProjectedHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActualHours")]
        public double? ActualHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SelectedEquipmentIds")]
        public IList<long?> SelectedEquipmentIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EquipmentList")]
        public IList<SelectListItem> EquipmentList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderNumber")]
        public long? WorkOrderNumber { get; set; }

    }
}
