// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class OccurrenceInfo
    {
        /// <summary>
        /// Initializes a new instance of the OccurrenceInfo class.
        /// </summary>
        public OccurrenceInfo() { }

        /// <summary>
        /// Initializes a new instance of the OccurrenceInfo class.
        /// </summary>
        public OccurrenceInfo(long? id = default(long?), DateTime? setupTime = default(DateTime?), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? tearDownTime = default(DateTime?))
        {
            Id = id;
            SetupTime = setupTime;
            StartTime = startTime;
            EndTime = endTime;
            TearDownTime = tearDownTime;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SetupTime")]
        public DateTime? SetupTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartTime")]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndTime")]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TearDownTime")]
        public DateTime? TearDownTime { get; set; }

    }
}
