// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SelectListGroup
    {
        /// <summary>
        /// Initializes a new instance of the SelectListGroup class.
        /// </summary>
        public SelectListGroup() { }

        /// <summary>
        /// Initializes a new instance of the SelectListGroup class.
        /// </summary>
        public SelectListGroup(bool? disabled = default(bool?), string name = default(string))
        {
            Disabled = disabled;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Disabled")]
        public bool? Disabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

    }
}
