// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class VmAllocatedQuantityInSpace
    {
        /// <summary>
        /// Initializes a new instance of the VmAllocatedQuantityInSpace class.
        /// </summary>
        public VmAllocatedQuantityInSpace() { }

        /// <summary>
        /// Initializes a new instance of the VmAllocatedQuantityInSpace class.
        /// </summary>
        public VmAllocatedQuantityInSpace(int quantity, long? scheduledSpaceId = default(long?), string spaceName = default(string))
        {
            Quantity = quantity;
            ScheduledSpaceId = scheduledSpaceId;
            SpaceName = spaceName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public int Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ScheduledSpaceId")]
        public long? ScheduledSpaceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SpaceName")]
        public string SpaceName { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
