// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class WorkOrderItemCreateOrUpdate
    {
        /// <summary>
        /// Initializes a new instance of the WorkOrderItemCreateOrUpdate
        /// class.
        /// </summary>
        public WorkOrderItemCreateOrUpdate() { }

        /// <summary>
        /// Initializes a new instance of the WorkOrderItemCreateOrUpdate
        /// class.
        /// </summary>
        public WorkOrderItemCreateOrUpdate(long? workOrderId = default(long?), long? workOrderNumber = default(long?), double? estimatedMaterialsCost = default(double?), double? estimatedLaborCost = default(double?), double? actualMaterialsCost = default(double?), double? actualLaborCost = default(double?), int? costType = default(int?), IList<SelectListItem> inventoryTypesSelectListItems = default(IList<SelectListItem>), IList<SelectListItem> equipmentSelectListItems = default(IList<SelectListItem>), long? locationId = default(long?), string miscCostItemName = default(string), long? equipmentId = default(long?), int? quantity = default(int?), string notes = default(string), long? inventoryItemId = default(long?), long? id = default(long?), string eqName = default(string), string inventoryName = default(string), bool? isSuccessStatusCode = default(bool?), string errorCode = default(string), string message = default(string))
        {
            WorkOrderId = workOrderId;
            WorkOrderNumber = workOrderNumber;
            EstimatedMaterialsCost = estimatedMaterialsCost;
            EstimatedLaborCost = estimatedLaborCost;
            ActualMaterialsCost = actualMaterialsCost;
            ActualLaborCost = actualLaborCost;
            CostType = costType;
            InventoryTypesSelectListItems = inventoryTypesSelectListItems;
            EquipmentSelectListItems = equipmentSelectListItems;
            LocationId = locationId;
            MiscCostItemName = miscCostItemName;
            EquipmentId = equipmentId;
            Quantity = quantity;
            Notes = notes;
            InventoryItemId = inventoryItemId;
            Id = id;
            EqName = eqName;
            InventoryName = inventoryName;
            IsSuccessStatusCode = isSuccessStatusCode;
            ErrorCode = errorCode;
            Message = message;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderId")]
        public long? WorkOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkOrderNumber")]
        public long? WorkOrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EstimatedMaterialsCost")]
        public double? EstimatedMaterialsCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EstimatedLaborCost")]
        public double? EstimatedLaborCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActualMaterialsCost")]
        public double? ActualMaterialsCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActualLaborCost")]
        public double? ActualLaborCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CostType")]
        public int? CostType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InventoryTypesSelectListItems")]
        public IList<SelectListItem> InventoryTypesSelectListItems { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EquipmentSelectListItems")]
        public IList<SelectListItem> EquipmentSelectListItems { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LocationId")]
        public long? LocationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MiscCostItemName")]
        public string MiscCostItemName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EquipmentId")]
        public long? EquipmentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public int? Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Notes")]
        public string Notes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InventoryItemId")]
        public long? InventoryItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EqName")]
        public string EqName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InventoryName")]
        public string InventoryName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsSuccessStatusCode")]
        public bool? IsSuccessStatusCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

    }
}
