// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ESpace
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// EventsList operations.
    /// </summary>
    public partial interface IEventsList
    {
        /// <param name='apiKey'>
        /// </param>
        /// <param name='eventId'>
        /// </param>
        /// <param name='version'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> OccurrencesWithHttpMessagesAsync(string apiKey, long eventId, string version, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='apiKey'>
        /// </param>
        /// <param name='occurrenceId'>
        /// </param>
        /// <param name='version'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> OccurrenceWithHttpMessagesAsync(string apiKey, long occurrenceId, string version, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='apiKey'>
        /// </param>
        /// <param name='version'>
        /// </param>
        /// <param name='eventId'>
        /// </param>
        /// <param name='nextDays'>
        /// </param>
        /// <param name='eventName'>
        /// </param>
        /// <param name='startDate'>
        /// </param>
        /// <param name='endDate'>
        /// </param>
        /// <param name='categoryIds'>
        /// </param>
        /// <param name='locationIds'>
        /// </param>
        /// <param name='externalId'>
        /// </param>
        /// <param name='createdDateFrom'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> ListWithHttpMessagesAsync(string apiKey, string version, long? eventId = default(long?), int? nextDays = default(int?), string eventName = default(string), string startDate = default(string), string endDate = default(string), string categoryIds = default(string), string locationIds = default(string), string externalId = default(string), string createdDateFrom = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
