// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Touchpoint.Cms.Integrations.ESpace
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Items.
    /// </summary>
    public static partial class ItemsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='apiKey'>
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='type'>
            /// </param>
            /// <param name='itemId'>
            /// </param>
            public static object List(this IItems operations, string apiKey, string version, string type = default(string), long? itemId = default(long?))
            {
                return Task.Factory.StartNew(s => ((IItems)s).ListAsync(apiKey, version, type, itemId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='apiKey'>
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='type'>
            /// </param>
            /// <param name='itemId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ListAsync(this IItems operations, string apiKey, string version, string type = default(string), long? itemId = default(long?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListWithHttpMessagesAsync(apiKey, version, type, itemId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
